#trigger github action again
name: Terraform Deployment

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  
jobs:
  deploy-cluster:
    runs-on: ubuntu-latest

    env:

        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-01

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: TF_LOG=DEBUG terraform init #-reconfigure

    - name: Terraform format
      run: terraform fmt
    
    - name: Terraform validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Create master node first
      if: github.ref == 'refs/heads/main'
      run: terraform apply -target=aws_eks_cluster.eks_cluster -auto-approve

    - name: Generate kubeconfig
      run: |
        mkdir -p $HOME/.kube
        aws eks update-kubeconfig --region eu-north-01 --name minimal-eks-cluster --kubeconfig $HOME/.kube/config
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Upload kubeconfig as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: kubeconfig
        path: $HOME/.kube/config
  
  deploy-worknode:
    runs-on: ubuntu-latest
    needs: deploy-cluster
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download kubeconfig
        uses: actions/download-artifact@v3
        with:
          name: kubeconfig
          path: $HOME/.kube/

      - name: Set KUBECONFIG Environment Variable
        run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Verify kubectl Access
        run: kubectl get nodes

      - name: Apply Worker Nodes & Kubernetes Resources
        run: terraform apply -auto-approve