#trigger github action again
name: Terraform Deployment

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  
jobs:
  deploy-cluster:
    runs-on: ubuntu-latest

    env:

        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: TF_LOG=DEBUG terraform init #-reconfigure

    - name: Terraform format
      run: terraform fmt
    
    - name: Terraform validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Create master node first
      if: github.ref == 'refs/heads/main'
      run: terraform apply -target=aws_eks_cluster.eks_cluster -auto-approve
    
    - name: Install AWS CLI (if missing)
      run: |
        if ! command -v aws &> /dev/null; then
          echo "Installing AWS CLI..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        else
          echo "AWS CLI is already installed."
        fi

    - name: Verify AWS Identity
      run: aws sts get-caller-identity

    - name: Generate kubeconfig
      run: |
        mkdir -p /home/runner/.kube
        aws eks update-kubeconfig --region eu-north-1 --name minimal-eks-cluster --kubeconfig /home/runner/.kube/config
      env:
        KUBECONFIG: /home/runner/.kube/config

    - name: Check EKS Cluster Status
      run: aws eks describe-cluster --name minimal-eks-cluster --query "cluster.status"

    - name: Debug kubeconfig Path
      run: |
        ls -lah /home/runner/.kube
        cat /home/runner//.kube/config || echo "❌ kubeconfig file not found!"

    - name: Upload kubeconfig as an artifact
      uses: actions/upload-artifact@v4   #artifact v3 has deprecated
      with:
        name: kubeconfig
        path: /home/runner/.kube/config
  
  deploy-worknode:
    runs-on: ubuntu-latest
    needs: deploy-cluster
    env:

        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download kubeconfig
        uses: actions/download-artifact@v4
        with:
          name: kubeconfig
          path: /home/runner/.kube/

      - name: Check if kubeconfig exists
        run: |
          if [ -f "/home/runner/.kube/config" ]; then
            echo "✅ kubeconfig exists!"
            cat /home/runner/.kube/config
          else
            echo "❌ kubeconfig was NOT created!"
            exit 1
          fi

      - name: Set KUBECONFIG Environment Variable
        run: echo "KUBECONFIG=/home/runner/.kube/config" >> $GITHUB_ENV

      - name: Verify kubectl Access
        run: kubectl get nodes


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
  
      - name: Terraform Init
        run: TF_LOG=DEBUG terraform init #-reconfigure
  
      - name: Terraform format
        run: terraform fmt
      
      - name: Terraform validate
        run: terraform validate
  
      - name: Terraform Plan
        run: terraform plan

      - name: Apply Worker Nodes & Kubernetes Resources
        run: terraform apply -auto-approve

      - name: Verify EKS Node Group Status
        run: aws eks describe-nodegroup --cluster-name minimal-eks-cluster --nodegroup-name minimal-node-group
      
      - name: Test EKS Nodes
        run: |
          kubectl get nodes || echo "❌ Nodes not found! Possible failure in joining the cluster."